### ISSUE TITLE
Examples migration tracking 

### ISSUE THREAD

**Issue by msutkowski** [reduxjs/redux-toolkit#1102]
- [x] Getting started: basic - #1101 
- [x] Getting started: advanced - #1101 
- [x] Concepts: Optimistic Updates - #1095 
- [x] Concepts: Conditional Fetching - #1104 
- [x] Concepts: Mutations - #1104 
- [x] Concepts: Queries Deduping Caching
- [x] Concepts: Prefetching - #1105
- [x] Concepts: Prefetching Automatic - #1105
- [x] Concepts: Prefetching Automatic Waterfall - #1105
- [x] Concepts: Polling - #1107
- [ ] Concepts: Code Splitting ?
- [x] Concepts: Pagination - #1107
- [x] Examples: GraphQL Basic - #1109
- [x] Examples: GraphQL Advanced - #1111 (WIP - pending `@mswjs/data` updates)
- [x] Examples: ApiProvider - #1106 
- [ ] Examples: React Class Component
- [x] Examples: Authentication - #1108
- [x] Examples: Authentication w/ Extra Reducers - #1108
- [ ] Examples: Svelte
- [ ] Cache Subscription Lifetime - https://deploy-preview-1092--redux-starter-kit-docs.netlify.app/rtk-query/usage/cache-behavior#cache-subscription-lifetime-demo
