### ISSUE TITLE
Migrate RSK to "Redux Toolkit"

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#248]
Following up from #246 :

## Tasks

- [x]  New `redux-toolkit.js.org` domain name
    - [x] Ask for instructions on handling the switch ( https://github.com/js-org/js.org/issues/3532 )
    - [x] Follow steps for changing over
    - [x] Ensure new `redux-toolkit.js.org` name points to the site
    - [x] Ensure current `redux-starter-kit.js.org` name redirects or points to the new site
- [x] Publish the new package name
    - [x] Rename package in `package.json`
    - [x] Rename Github repo
    - [x] Change URL of repo
    - [x] Update README
    - [x] Update UMD global variable name to `RTK`
    - [x] Publish new version
    - [x] Merge in new docs site
- [x] Force people to migrate to the new package
    - [x] Publish updated version of RSK that throws an error and prints a "Please migrate..." message
    - [x] Deprecate RSK versions ( https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions )
- [x] Update docs content
    - [x] Rewrite all the docs content to scrub and update the package name, the actual name, and the abbreviations
    - [x] Re-create / update tutorial sandboxes and repos using new package name
- [x] Come up with a single "sales pitch" description line.  I've been using multiple variations in different places, and it would be nice to have something short, descriptive, and consistent.
- [x] Update other Redux docs
    - [x] Redux core docs (front link and content)
    - [x] React-Redux docs (front link)
- [x] Update other content
    - [x] Update title and content of my own blog post: https://blog.isquaredsoftware.com/2019/10/redux-starter-kit-1.0/
    - [x] Go search for other discussions of RSK and rename if possible
- [x] General announcements

**Comment by nickmccurdy** [comment]
I'd recommend using `npm deprecate` rather than throwing an error, as the package manager will be able to deal with the warnings at build time and the data will be machine readable

**Comment by markerikson** [comment]
I did `npm deprecate` as soon as I published RTK for the first time.  React Testing Library did the "publish a new version with an error message" thing, so there's precedent.  (I think they specifically did it as a major for `react-testing-library`, which is probably the nicer way to handle it.)

https://redux-starter-kit.js.org still exists as a domain name, but it points to the same Netlify server, so I would hope that would kind of be a clue :)

**Comment by markerikson** [comment]
Just published RSK 2.0, which removes all the code and throws the "migrate to RTK" error message:

https://github.com/reduxjs/redux-toolkit/releases/tag/v1.0.4

That wraps things up here.
