### ISSUE TITLE
compressed-size-action replacement tracker

### ISSUE THREAD

**Issue by msutkowski** [reduxjs/redux-toolkit#635]
Original context here: https://github.com/reduxjs/redux-toolkit/pull/632

To evaluate:
- [x] Supposedly https://github.com/kuldeepkeshwar/size-plugin-bot works better because it's a bot and not an action, or so the author told me.
  - **tl:dr; I don't trust this lib to have the permissions it requests and documentation is lacking.** You need a PHD to figure out how to configure this, and I'm short on that, unfortunately. In general, I would not recommend this as it asks for overzealous GitHub permissions and looks like it can possibly rewrite branches and be destructive. I wouldn't have a problem with that, but the code base is a little bit of a 🔥 and references a lot of the authors WIP libs that specifically say to not use for anything other than hobby projects? As a comparison, all of these type of libs basically just use github status checks - this one tries to do _much more_.
- [x] https://github.com/bundlewatch/bundlewatch#i-use-bundlesize-why-should-i-switch-to-bundlewatch ?
     - I spent about 2 hours trying to get this to pass in a PR here, as well as on one of my own repos and kept running into walls. It seems like their service is down and not storing anything even though it's generating the output and a permalink. I could fork their service layer and spin up a quick instance and point to that, but that defeats the point of a managed service IMO. I will evaluate the other options before going that route.
- [x] https://github.com/ai/size-limit
  - I got this working, but it has the same issue as compressed-size-action regarding forked PRs. It'd need to have a service/github app layer added.
- [x] https://github.com/siddharthkp/bundlesize2
  - I got this working, but the GitHub App never posted back the status check results even though it `console.log`'d that it was 'working'. I realize this is still a WIP, but could possibly be picked up and moved along with a few contributions.
- [x] https://github.com/siddharthkp/bundlesize
  - I'm going to spin up a test repo with travis and see if I can get this to work as desired. This seems to be the most promising route at this point.

**Comment by msutkowski** [comment]
Updated notes. I'm going to ping the `bundlewatch` folks and see if they can let me know what the deal is on service failures. As of right now, that'd be my preferred choice. After that, I'll try the travis/bundlesize combo. After that, I'll just fork bundlewatch and bend it to my will 💪

**Comment by msutkowski** [comment]
Will be closed by #638 🎉

**Comment by phryneas** [comment]
Repopening this as #638 does not seem to be a viable solution

**Comment by msutkowski** [comment]
Tacking on a note: current thought process is to stand up a microservice + GitHub bot (based on [Probot](https://github.com/probot/probot)). I should be able to have something up by the EOW for sure. The ideal solution would borrow some of the infra from bundlesize2 and bundlewatch.

**Comment by markerikson** [comment]
We seem to have settled on https://github.com/ai/size-limit now.
